### ISSUE TITLE
 [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:bkash_next/config/env.dart' not found.

### ISSUE THREAD

**Issue by aktarulahsan** [codeboxrcodehub/flutter-bkash#11]
after payment this error sho  

[ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:bkash_next/config/env.dart' not found.

**Comment by rdnasim** [comment]
The package name is flutter_bkash

Error show on your comment as bkash_next. Please user proper package and get feedback to us.

**Comment by aktarulahsan** [comment]
I use flutter_bkash: ^0.2.0 in my project, and I use my real Bkash Credentials as Production, when I request payment then this error shows.

**Comment by rdnasim** [comment]
but where are you found library 'package:bkash_next/config/env.dart'
This is not our library. Please recheck again and again.

**Comment by aktarulahsan** [comment]
on console

**Comment by rdnasim** [comment]
This Issue is not valid, that's why close this issue. Thanks for your issue @aktarulahsan

Regards
@rdnasim
