### ISSUE TITLE
No payment window popups when isSandbox  is set to false.

### ISSUE THREAD

**Issue by ahnaf16** [codeboxrcodehub/flutter-bkash#3]
This is where I'm stuck. Nothing is happening after this.
![image](https://user-images.githubusercontent.com/55395335/214553684-ee76a01e-afda-469c-92f8-f15ac3130dbd.png)
This is my code. (copy pasted from the repo)

```
BkashPayment(
      isSandbox: false,
      amount: '20',
      intent: 'sale',
      // accessToken: '',
      currency: 'BDT',
      createBKashUrl:
          'https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/create',
      executeBKashUrl:
          'https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/execute',
      scriptUrl: 'https://scripts.pay.bka.sh/versions/1.2.0-beta/checkout/bKash-checkout.js',
      paymentStatus: (status, data) {
        log('return status => $status');
        log('return data => $data');
      {...}
    );
```

**Comment by rdnasim** [comment]
Hello Brother,

If you need to set isSandbox as 'false', then ensure to keep custom createBKashUrl and executeBKashUrl. Which means you are on the production environment.

Thanks

**Comment by ahnaf16** [comment]
> Hello Brother,
> 
> If you need to set isSandbox as 'false', then ensure to keep custom createBKashUrl and executeBKashUrl. Which means you are on the production environment.
> 
> Thanks

I don't think I got that, but did you mean tokenized url won't work? Instead I need to use merchants payment url?

**Comment by ratulhasanruhan** [comment]
I have the same issue. I create a custom backend but it's same

**Comment by ahnaf16** [comment]
> Hello Brother,
> 
> If you need to set isSandbox as 'false', then ensure to keep custom createBKashUrl and executeBKashUrl. Which means you are on the production environment.
> 
> Thanks

@rdnasim  So do I need to create a custom API on my backend that will handle the payment creation and execution? Do I need a custom Script also?

**Comment by rdnasim** [comment]
Sorry for this trouble. Bkash changed there payment process. Need to update this package. I have not enough time to update this. But it will update inshaAllah.

I suggest to you, please follow bkash [documentation](https://developer.bka.sh/reference/createpaymentusingpost). It will be more helpful.
