### ISSUE TITLE
Kindly update support for Bkash tokenizer API [Enhancement] 

### ISSUE THREAD

**Issue by hmbadhon** [codeboxrcodehub/flutter-bkash#4]
@manchumahara @rdnasim 
https://developer.bka.sh/docs/grant-token-1

**Comment by rdnasim** [comment]
Hi @hmbadhon you can send PR to dev branch for Bkash tokenizer API

**Comment by hmbadhon** [comment]
i was hoping to get update from you. @rdnasim

**Comment by rdnasim** [comment]
Sure, I'd be happy to give you an update. InshaAllah, It will be take time as per my flexible time schedule. @hmbadhon

**Comment by rdnasim** [comment]
Hello Dear @hmbadhon,

Now you can use it as tokenized based payment.

Regards
Riadul

--Close as it resolved the issues--
