### ISSUE TITLE
Where can I change my api credentials?

### ISSUE THREAD

**Issue by ratulhasanruhan** [codeboxrcodehub/flutter-bkash#5]

**Comment by rdnasim** [comment]
Hello @ratulhasanruhan,

Can you please more describe your current scenario about this issues? It more helpful for understanding.

Regards
Riadul

**Comment by ratulhasanruhan** [comment]
I made a backend with this API file: https://github.com/Mominulcse7/bKash_Integration/blob/master/BkashApiFile.zip

and Added changes like this:
createBKashUrl: 'https://telicombd.com/bkash/createpayment.php',

 executeBKashUrl: 'https://telicombd.com/bkash/executepayment.php',

isSandbox: false,

But not showing the payment Screen.

**Comment by ratulhasanruhan** [comment]
@rdnasim Please help me to solve it.

**Comment by rdnasim** [comment]
@ratulhasanruhan Now you can change your api credentials as tokenized based payment.
