### ISSUE TITLE
Can't open keyboard on pop-up;  Error: Expecting binder but got null!

### ISSUE THREAD

**Issue by whatknot23** [codeboxrcodehub/flutter-bkash#9]
https://drive.google.com/file/d/1fXKU9YIKmR9bLR939VNMPbIxd-4fe_nY/view?usp=drive_link

I'm using Getx state management. I've WidgetsFlutterBinding.ensureInitialized(); on my main. 
Not sure how to go about it.

**Comment by rdnasim** [comment]
Not found the drive file. I am sorry to late reply.

Next time, I will reply on time.
